server:
  port: 8087

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: CandidatService
          uri: http://localhost:8081
          predicates:
            - Path=/candidat/**
        - id: TestService
          uri: http://localhost:8080
          predicates:
            - Path=/tests/**
        - id: LevelService
          uri: http://localhost:8083
          predicates:
            - Path=/level/**
        - id: RoleService
          uri: http://localhost:8082
          predicates:
            - Path=/role/**
        - id: ThemeService
          uri: http://localhost:8085
          predicates:
            - Path=/theme/**
        - id: ScoreService
          uri: http://localhost:8086
          predicates:
            - Path=/score/**
        - id: Authentification
          uri: http://localhost:8088
          predicates:
            - Path=/api/**
        - id: CompetenceService
          uri: http://localhost:8089
          predicates:
            - Path=/competences/**
        - id: QuestionService
          uri: http://localhost:8090
          predicates:
            - Path=/question/**
        - id: AnswerService
          uri: http://localhost:8091
          predicates:
            - Path=/answer/**
